[[themes]]
name = "AstroJupiter"
[themes.palette]
background = "#FEEEEE"
foreground = "#815654"
black = "#D8D6D5"
red = "#A13F37"
green = "#467118"
yellow = "#805C00"
blue = "#006E89"
magenta = "#90437A"
cyan = "#007652"
white = "#9E7876"
bright_black = "#B0AEAD"
bright_red = "#C9675F"
bright_green = "#6E9940"
bright_yellow = "#A88428"
bright_blue = "#2896B1"
bright_magenta = "#B86BA2"
bright_cyan = "#289E7A"
bright_white = "#8B605E"
