[[themes]]
name = "AstroMars"
[themes.palette]
background = "#1E1517"
foreground = "#A5B2BC"
black = "#281E22"
red = "#DF8489"
green = "#84A860"
yellow = "#C3963D"
blue = "#4FA9C6"
magenta = "#CD87BA"
cyan = "#4FAD97"
white = "#8B7079"
bright_black = "#41383A"
bright_red = "#FFA7AC"
bright_green = "#A7CB83"
bright_yellow = "#E6B960"
bright_blue = "#72CCE9"
bright_magenta = "#F0AADD"
bright_cyan = "#72D0BA"
bright_white = "#C8D5DF"
