[[themes]]
name = "AstroDark"
[themes.palette]
background = "#1A1D23"
foreground = "#ADB0BB"
black = "#111317"
red = "#FF838B"
green = "#87C05F"
yellow = "#DFAB25"
blue = "#5EB7FF"
magenta = "#DD97F1"
cyan = "#4AC2B8"
white = "#9B9FA9"
bright_black = "#34363A"
bright_red = "#FFA6AE"
bright_green = "#AAE382"
bright_yellow = "#FFCE48"
bright_blue = "#81DAFF"
bright_magenta = "#FFBAFF"
bright_cyan = "#6DE5DB"
bright_white = "#D0D3DE"
