[[themes]]
name = "AstroLight"
[themes.palette]
background = "#F7F8F8"
foreground = "#4F4F4F"
black = "#E1E2E4"
red = "#990000"
green = "#345E00"
yellow = "#7300B8"
blue = "#00508A"
magenta = "#9E007C"
cyan = "#00615B"
white = "#737474"
bright_black = "#B9BABC"
bright_red = "#C12828"
bright_green = "#5C8628"
bright_yellow = "#9B28E0"
bright_blue = "#2878B2"
bright_magenta = "#C628A4"
bright_cyan = "#288983"
bright_white = "#595959"
