attribute = { fg = "#7300B8" }
comment = { fg = "#8B9297", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#345E00" }
constant = { fg = "#7300B8" }
"constant.builtin" = { fg = "#7300B8" }
"constant.builtin.boolean" = { fg = "#A34500" }
"constant.character" = { fg = "#345E00" }
"constant.character.escape" = { fg = "#990000" }
"constant.numeric" = { fg = "#A34500" }
"constant.numeric.float" = { fg = "#7300B8" }
"constant.numeric.integer" = { fg = "#A34500" }
constructor = { fg = "#00508A" }
"diagnostic.error" = { underline = { color = "#E72F1F", style = "curl" } }
"diagnostic.hint" = { underline = { color = "#21B386", style = "curl" } }
"diagnostic.info" = { underline = { color = "#3F8CEA", style = "curl" } }
"diagnostic.warning" = { underline = { color = "#E69400", style = "curl" } }
error = { fg = "#E72F1F" }
function = { fg = "#00508A" }
"function.builtin" = { fg = "#00615B" }
"function.macro" = { fg = "#7300B8" }
"function.method" = { fg = "#00508A" }
"function.special" = { fg = "#7300B8" }
hint = { fg = "#21B386" }
info = { fg = "#3F8CEA" }
keyword = { fg = "#9E007C" }
"keyword.control" = { fg = "#9E007C" }
"keyword.control.conditional" = { fg = "#9E007C" }
"keyword.control.exception" = { fg = "#9E007C" }
"keyword.control.repeat" = { fg = "#9E007C" }
"keyword.control.return" = { fg = "#9E007C" }
"keyword.directive" = { fg = "#7300B8" }
"keyword.function" = { fg = "#9E007C" }
"keyword.operator" = { fg = "#9E007C" }
label = { fg = "#00508A" }
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = { fg = "#4F4F4F", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "#E1E2E3", fg = "#737474" }
"markup.heading.hover" = { bg = "#E7E9EB", modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link" = { fg = "#7300B8", modifiers = ["bold"] }
"markup.link.label" = { fg = "#345E00" }
"markup.link.text" = { fg = "#7300B8", modifiers = ["bold"] }
"markup.link.url" = { fg = "#00508A", modifiers = ["italic"], underline = { style = "line" } }
"markup.list" = { fg = "#00508A" }
"markup.raw" = { fg = "#990000" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#9E007C" }
operator = { fg = "#4F4F4F" }
special = { fg = "#00508A" }
string = { fg = "#345E00" }
"string.regexp" = { fg = "#345E00" }
"string.special" = { fg = "#345E00" }
tag = { fg = "#990000" }
type = { fg = "#00508A" }
"type.builtin" = { fg = "#7300B8" }
"type.enum" = { fg = "#00508A" }
"type.enum.variant" = { fg = "#7300B8" }
"ui.background" = { bg = "bg" }
"ui.cursor" = { bg = "#737474", fg = "#F7F8F8" }
"ui.cursor.match" = { fg = "#F0740A", modifiers = ["bold"] }
"ui.linenr" = { fg = "#B5B9BD" }
"ui.linenr.select" = { fg = "#424446" }
"ui.menu" = { bg = "#E1E2E3", fg = "#737474" }
"ui.menu.scroll" = { bg = "#E1E2E3", fg = "#671FF0" }
"ui.menu.selected" = { bg = "#E7E9EB", modifiers = ["bold"] }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#E1E2E4", fg = "#737474" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#F7F8F8", fg = "#4F4F4F" }
"ui.text.focus" = { bg = "#E7E9EB" }
"ui.text.inactive" = { fg = "#8B9297", modifiers = ["italic"] }
"ui.window" = { bg = "#F7F8F8", fg = "#E8E9EA" }
variable = { fg = "#4F4F4F" }
"variable.builtin" = { fg = "#00615B" }
"variable.other.member" = { fg = "#990000" }
"variable.parameter" = { fg = "#A34500" }
warning = { fg = "#E69400" }

[palette]
"icon.c" = "#519aba"
"icon.css" = "#61afef"
"icon.deb" = "#a1b7ee"
"icon.docker" = "#384d54"
"icon.html" = "#de8c92"
"icon.jpeg" = "#c882e7"
"icon.jpg" = "#c882e7"
"icon.js" = "#ebcb8b"
"icon.jsx" = "#519ab8"
"icon.kt" = "#7bc99c"
"icon.lock" = "#c4c720"
"icon.lua" = "#51a0cf"
"icon.md" = "#519aba"
"icon.mp3" = "#d39ede"
"icon.mp4" = "#9ea3de"
"icon.out" = "#abb2bf"
"icon.pkg" = "#d39ede"
"icon.png" = "#c882e7"
"icon.py" = "#a3b8ef"
"icon.rb" = "#ff75a0"
"icon.robots" = "#abb2bf"
"icon.rpm" = "#fca2aa"
"icon.rs" = "#dea584"
"icon.toml" = "#39bf39"
"icon.ts" = "#519aba"
"icon.ttf" = "#abb2bf"
"icon.vue" = "#7bc99c"
"icon.woff" = "#abb2bf"
"icon.woff2" = "#abb2bf"
"icon.zip" = "#f9d71c"
"syntax.blue" = "#00508A"
"syntax.comment" = "#8B9297"
"syntax.cyan" = "#00615B"
"syntax.green" = "#345E00"
"syntax.mute" = "#8B9297"
"syntax.orange" = "#A34500"
"syntax.purple" = "#9E007C"
"syntax.red" = "#990000"
"syntax.text" = "#4F4F4F"
"syntax.yellow" = "#7300B8"
"term.background" = "#F7F8F8"
"term.black" = "#E1E2E4"
"term.blue" = "#00508A"
"term.bright_black" = "#B9BABC"
"term.bright_blue" = "#2878B2"
"term.bright_cyan" = "#288983"
"term.bright_green" = "#5C8628"
"term.bright_purple" = "#C628A4"
"term.bright_red" = "#C12828"
"term.bright_white" = "#595959"
"term.bright_yellow" = "#9B28E0"
"term.cyan" = "#00615B"
"term.foreground" = "#737474"
"term.green" = "#345E00"
"term.purple" = "#9E007C"
"term.red" = "#990000"
"term.white" = "#737474"
"term.yellow" = "#7300B8"
"ui.accent" = "#671FF0"
"ui.base" = "#F7F8F8"
"ui.blue" = "#3F8CEA"
"ui.border" = "#671FF0"
"ui.current_line" = "#EAEBEB"
"ui.cyan" = "#21B386"
"ui.float" = "#E1E2E3"
"ui.green" = "#42AD17"
"ui.highlight" = "#DADBDD"
"ui.inactive_base" = "#EAEBEB"
"ui.menu_selection" = "#E7E9EB"
"ui.none_text" = "#B5B9BD"
"ui.orange" = "#F0740A"
"ui.prompt" = "#F0F0F1"
"ui.purple" = "#671FF0"
"ui.red" = "#E72F1F"
"ui.scrollbar" = "#671FF0"
"ui.selection" = "#E7E9EB"
"ui.split" = "#E8E9EA"
"ui.statusline" = "#E1E2E4"
"ui.tabline" = "#E1E2E4"
"ui.text" = "#737474"
"ui.text_active" = "#424446"
"ui.text_inactive" = "#AEB3B6"
"ui.text_match" = "#17191C"
"ui.title" = "#671FF0"
"ui.tool" = "#F0F0F1"
"ui.winbar" = "#999FA3"
"ui.yellow" = "#E69400"