[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# highlight = "path/to/tmTheme"

cwd = { fg = "#68545B", italic = true }

# Hovered
hovered         = { bg = "#1B282C" }
preview_hovered = { bg = "#1B282C" }

# Find
find_keyword  = { fg = "#1E1517", bg = "#FAA27F", bold = true }
find_position = { fg = "#9CBDC9", bg = "#1B282C", bold = true }

# Marker
marker_copied   = { fg = "#9AC374", bg = "#9AC374" }
marker_cut      = { fg = "#E77777", bg = "#E77777" }
marker_marked   = { fg = "#E8A1D7", bg = "#E8A1D7" }
marker_selected = { fg = "#9CBDC9", bg = "#9CBDC9" }

# Tab
tab_active   = { fg = "#A5B2BC", bg = "#1E1517" }
tab_inactive = { fg = "#68545B", bg = "#281E22" }
tab_width    = 1

# Count
count_copied   = { fg = "#8B7079", bg = "#9AC374" }
count_cut      = { fg = "#8B7079", bg = "#E77777" }
count_selected = { fg = "#8B7079", bg = "#9CBDC9" }
# Border
border_symbol = "│"
border_style  = { fg = "#736468" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#393337", bg = "#393337" }

# Mode
mode_normal = { fg = "#1E1517", bg = "#9CBDC9", bold = true }
mode_select = { fg = "#1E1517", bg = "#E8A1D7", bold = true }
mode_unset  = { fg = "#1E1517", bg = "#E77777", bold = true }

# Progress
progress_label  = { fg = "#68545B", bold = true }
progress_normal = { fg = "#1E1517" }
progress_error  = { fg = "#E77777" }

# Permissions
permissions_t = { fg = "#9CBDC9" }
permissions_r = { fg = "#FFA31A" }
permissions_w = { fg = "#E77777" }
permissions_x = { fg = "#9AC374" }
permissions_s = { fg = "#393337" }

[select]
border   = { fg = "#736468" }
active   = { fg = "#8B7079",  bg = "#1B282C" }
inactive = { fg = "#8B7079" }

# Input
[input]
border   = { fg = "#9CBDC9" }
title    = { fg = "#9CBDC9" }
value    = { fg = "#E8A1D7" }
selected = { bg = "#1B282C" }

# Completion
[completion]
border   = { fg = "#9CBDC9" }
active   = { fg = "#8B7079", bg = "#1B282C" }
inactive = { fg = "#8B7079" }

# Tasks
[tasks]
border  = { fg = "#736468" }
title   = { fg = "#9CBDC9" }
hovered = { fg = "#8B7079", bg="#1B282C" }

# Which
[which]
cols = 3
mask            = { bg = "#1A1113" }
cand            = { fg = "#88C3AB" }
rest            = { fg = "#9CBDC9" }
desc            = { fg = "#E8A1D7" }
separator       = "  "
separator_style = { fg = "#393337" }

# Notify
[notify]
title_info  = { fg = "#9CBDC9" }
title_warn  = { fg = "#FFA31A" }
title_error = { fg = "#E77777" }

# Help
[help]
on      = { fg = "#9AC374" }
run     = { fg = "#E8A1D7" }
hovered = { bg = "#1B282C" }
footer  = { fg = "#8B7079", bg = "#1E1517" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#C3963D" },

	# Media
	{ mime = "{audio,video}/*", fg = "#CD87BA" },

	# Archives
	{ mime = "application/*zip", fg = "#DF8489" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#DF8489" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#4FAD97" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#DF8489" },

	# Special files
	{ name = "*", is = "orphan", bg = "#DF8489" },
	{ name = "*", is = "exec"  , fg = "#84A860" },

	# Fallback
	{ name = "*/", fg = "#4FA9C6" }
]
